### ISSUE TITLE
Just doesn't work anymore

### ISSUE THREAD

**Issue by NeemaToto** [CelestialReaver/BetterDiscord#12]
Changes the font to a weird Serif and does nothing otherwise.

**Comment by CRYPTO-GENIK** [comment]
prob because Discord is a next.js / react type  app and they updated their framework and/or rebuild the build cache which changed all the classes for all the styles in Discord.

The author would need to find/replace them all one by one and then make corrections to anything else changed by the update.

In otherwords all the style id's now have the wrong name associated with the element they refrence

**Comment by NeemaToto** [comment]
Woah that'd be a pain. Unfortunate.
